remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Dron eskola irekia
description: Drone eta urrutiko gailuen tinker eskola irekia
show_downloads: true
google_analytics:
collections:
  pages:
    output: true
    permalink: /_pages/
