remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
lang: 'eu'
title: Drone eskola irekia
description: Indoor, jostailuzko, cinewhoop eta erabilera orokorreko drone eta urrutiko gailuen tinker eskola irekia bildu dugu espazio honetan. Webgune honetan dronen inguruko informazio guztia aurkituko duzu. Dronen arautegia eta erregulazioa, hardwarea, softwarea, berriak eta abar. Dronen inguruko informazio guztia edonork ulertzeko moduan eta era librean gizarteratzea da gure helburua, dronen konplexutasunak sinplifikatu eta horiekin gozatzeko.
show_downloads: true
google_analytics: G-XJ14B87QBH
collections:
  pages:
    output: true
    permalink: /_pages/
